### ISSUE TITLE
Is there a difference between dirty bits and valid bits?

### ISSUE THREAD

**Issue by dmgilmour** [devoncallanan/trainwreck#13]

**Comment by ANW91** [comment]
Yes valid bit says whether or not the data in the spot is useable or not while dirty bit says whther or not the data has been changed if it has then it will need to be written back to memory

**Comment by dmgilmour** [comment]
What do you mean by useable for valid bit?

**Comment by ANW91** [comment]
If the data is invalid it is the same as the data not being there at all

**Comment by dmgilmour** [comment]
💯
